// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coupon.proto

package com.punyabagus.generalOnlineStore.pojo;

public final class CouponData {
  private CouponData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CouponOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Coupon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string code = 2;</code>
     */
    boolean hasCode();
    /**
     * <code>optional string code = 2;</code>
     */
    java.lang.String getCode();
    /**
     * <code>optional string code = 2;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>optional string desc = 3;</code>
     */
    boolean hasDesc();
    /**
     * <code>optional string desc = 3;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>optional string desc = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>optional int32 quantity = 4;</code>
     */
    boolean hasQuantity();
    /**
     * <code>optional int32 quantity = 4;</code>
     */
    int getQuantity();

    /**
     * <code>optional int64 startDate = 5;</code>
     */
    boolean hasStartDate();
    /**
     * <code>optional int64 startDate = 5;</code>
     */
    long getStartDate();

    /**
     * <code>optional int64 endDate = 6;</code>
     */
    boolean hasEndDate();
    /**
     * <code>optional int64 endDate = 6;</code>
     */
    long getEndDate();

    /**
     * <code>optional int32 discountNominal = 7;</code>
     */
    boolean hasDiscountNominal();
    /**
     * <code>optional int32 discountNominal = 7;</code>
     */
    int getDiscountNominal();

    /**
     * <code>optional int32 discountPercentage = 8;</code>
     */
    boolean hasDiscountPercentage();
    /**
     * <code>optional int32 discountPercentage = 8;</code>
     */
    int getDiscountPercentage();
  }
  /**
   * Protobuf type {@code Coupon}
   */
  public  static final class Coupon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Coupon)
      CouponOrBuilder {
    // Use Coupon.newBuilder() to construct.
    private Coupon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Coupon() {
      id_ = "";
      code_ = "";
      desc_ = "";
      quantity_ = 0;
      startDate_ = 0L;
      endDate_ = 0L;
      discountNominal_ = 0;
      discountPercentage_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Coupon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              code_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              desc_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              quantity_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              startDate_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              endDate_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              discountNominal_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              discountPercentage_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.punyabagus.generalOnlineStore.pojo.CouponData.internal_static_Coupon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.punyabagus.generalOnlineStore.pojo.CouponData.internal_static_Coupon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.class, com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object code_;
    /**
     * <code>optional string code = 2;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 3;
    private volatile java.lang.Object desc_;
    /**
     * <code>optional string desc = 3;</code>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string desc = 3;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string desc = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 4;
    private int quantity_;
    /**
     * <code>optional int32 quantity = 4;</code>
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 quantity = 4;</code>
     */
    public int getQuantity() {
      return quantity_;
    }

    public static final int STARTDATE_FIELD_NUMBER = 5;
    private long startDate_;
    /**
     * <code>optional int64 startDate = 5;</code>
     */
    public boolean hasStartDate() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 startDate = 5;</code>
     */
    public long getStartDate() {
      return startDate_;
    }

    public static final int ENDDATE_FIELD_NUMBER = 6;
    private long endDate_;
    /**
     * <code>optional int64 endDate = 6;</code>
     */
    public boolean hasEndDate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 endDate = 6;</code>
     */
    public long getEndDate() {
      return endDate_;
    }

    public static final int DISCOUNTNOMINAL_FIELD_NUMBER = 7;
    private int discountNominal_;
    /**
     * <code>optional int32 discountNominal = 7;</code>
     */
    public boolean hasDiscountNominal() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 discountNominal = 7;</code>
     */
    public int getDiscountNominal() {
      return discountNominal_;
    }

    public static final int DISCOUNTPERCENTAGE_FIELD_NUMBER = 8;
    private int discountPercentage_;
    /**
     * <code>optional int32 discountPercentage = 8;</code>
     */
    public boolean hasDiscountPercentage() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 discountPercentage = 8;</code>
     */
    public int getDiscountPercentage() {
      return discountPercentage_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, desc_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, quantity_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, startDate_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, endDate_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, discountNominal_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, discountPercentage_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, desc_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, quantity_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, startDate_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, endDate_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, discountNominal_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, discountPercentage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon)) {
        return super.equals(obj);
      }
      com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon other = (com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && getCode()
            .equals(other.getCode());
      }
      result = result && (hasDesc() == other.hasDesc());
      if (hasDesc()) {
        result = result && getDesc()
            .equals(other.getDesc());
      }
      result = result && (hasQuantity() == other.hasQuantity());
      if (hasQuantity()) {
        result = result && (getQuantity()
            == other.getQuantity());
      }
      result = result && (hasStartDate() == other.hasStartDate());
      if (hasStartDate()) {
        result = result && (getStartDate()
            == other.getStartDate());
      }
      result = result && (hasEndDate() == other.hasEndDate());
      if (hasEndDate()) {
        result = result && (getEndDate()
            == other.getEndDate());
      }
      result = result && (hasDiscountNominal() == other.hasDiscountNominal());
      if (hasDiscountNominal()) {
        result = result && (getDiscountNominal()
            == other.getDiscountNominal());
      }
      result = result && (hasDiscountPercentage() == other.hasDiscountPercentage());
      if (hasDiscountPercentage()) {
        result = result && (getDiscountPercentage()
            == other.getDiscountPercentage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode().hashCode();
      }
      if (hasDesc()) {
        hash = (37 * hash) + DESC_FIELD_NUMBER;
        hash = (53 * hash) + getDesc().hashCode();
      }
      if (hasQuantity()) {
        hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
        hash = (53 * hash) + getQuantity();
      }
      if (hasStartDate()) {
        hash = (37 * hash) + STARTDATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartDate());
      }
      if (hasEndDate()) {
        hash = (37 * hash) + ENDDATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEndDate());
      }
      if (hasDiscountNominal()) {
        hash = (37 * hash) + DISCOUNTNOMINAL_FIELD_NUMBER;
        hash = (53 * hash) + getDiscountNominal();
      }
      if (hasDiscountPercentage()) {
        hash = (37 * hash) + DISCOUNTPERCENTAGE_FIELD_NUMBER;
        hash = (53 * hash) + getDiscountPercentage();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Coupon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Coupon)
        com.punyabagus.generalOnlineStore.pojo.CouponData.CouponOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.punyabagus.generalOnlineStore.pojo.CouponData.internal_static_Coupon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.punyabagus.generalOnlineStore.pojo.CouponData.internal_static_Coupon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.class, com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder.class);
      }

      // Construct using com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        quantity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        startDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        endDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        discountNominal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        discountPercentage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.punyabagus.generalOnlineStore.pojo.CouponData.internal_static_Coupon_descriptor;
      }

      public com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon getDefaultInstanceForType() {
        return com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.getDefaultInstance();
      }

      public com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon build() {
        com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon buildPartial() {
        com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon result = new com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.quantity_ = quantity_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.startDate_ = startDate_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.endDate_ = endDate_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.discountNominal_ = discountNominal_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.discountPercentage_ = discountPercentage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon) {
          return mergeFrom((com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon other) {
        if (other == com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCode()) {
          bitField0_ |= 0x00000002;
          code_ = other.code_;
          onChanged();
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000004;
          desc_ = other.desc_;
          onChanged();
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasStartDate()) {
          setStartDate(other.getStartDate());
        }
        if (other.hasEndDate()) {
          setEndDate(other.getEndDate());
        }
        if (other.hasDiscountNominal()) {
          setDiscountNominal(other.getDiscountNominal());
        }
        if (other.hasDiscountPercentage()) {
          setDiscountPercentage(other.getDiscountPercentage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <code>optional string code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>optional string desc = 3;</code>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            desc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>optional int32 quantity = 4;</code>
       */
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 quantity = 4;</code>
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>optional int32 quantity = 4;</code>
       */
      public Builder setQuantity(int value) {
        bitField0_ |= 0x00000008;
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 quantity = 4;</code>
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000008);
        quantity_ = 0;
        onChanged();
        return this;
      }

      private long startDate_ ;
      /**
       * <code>optional int64 startDate = 5;</code>
       */
      public boolean hasStartDate() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 startDate = 5;</code>
       */
      public long getStartDate() {
        return startDate_;
      }
      /**
       * <code>optional int64 startDate = 5;</code>
       */
      public Builder setStartDate(long value) {
        bitField0_ |= 0x00000010;
        startDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 startDate = 5;</code>
       */
      public Builder clearStartDate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        startDate_ = 0L;
        onChanged();
        return this;
      }

      private long endDate_ ;
      /**
       * <code>optional int64 endDate = 6;</code>
       */
      public boolean hasEndDate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 endDate = 6;</code>
       */
      public long getEndDate() {
        return endDate_;
      }
      /**
       * <code>optional int64 endDate = 6;</code>
       */
      public Builder setEndDate(long value) {
        bitField0_ |= 0x00000020;
        endDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 endDate = 6;</code>
       */
      public Builder clearEndDate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        endDate_ = 0L;
        onChanged();
        return this;
      }

      private int discountNominal_ ;
      /**
       * <code>optional int32 discountNominal = 7;</code>
       */
      public boolean hasDiscountNominal() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 discountNominal = 7;</code>
       */
      public int getDiscountNominal() {
        return discountNominal_;
      }
      /**
       * <code>optional int32 discountNominal = 7;</code>
       */
      public Builder setDiscountNominal(int value) {
        bitField0_ |= 0x00000040;
        discountNominal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 discountNominal = 7;</code>
       */
      public Builder clearDiscountNominal() {
        bitField0_ = (bitField0_ & ~0x00000040);
        discountNominal_ = 0;
        onChanged();
        return this;
      }

      private int discountPercentage_ ;
      /**
       * <code>optional int32 discountPercentage = 8;</code>
       */
      public boolean hasDiscountPercentage() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 discountPercentage = 8;</code>
       */
      public int getDiscountPercentage() {
        return discountPercentage_;
      }
      /**
       * <code>optional int32 discountPercentage = 8;</code>
       */
      public Builder setDiscountPercentage(int value) {
        bitField0_ |= 0x00000080;
        discountPercentage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 discountPercentage = 8;</code>
       */
      public Builder clearDiscountPercentage() {
        bitField0_ = (bitField0_ & ~0x00000080);
        discountPercentage_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Coupon)
    }

    // @@protoc_insertion_point(class_scope:Coupon)
    private static final com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon();
    }

    public static com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Coupon>
        PARSER = new com.google.protobuf.AbstractParser<Coupon>() {
      public Coupon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Coupon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Coupon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Coupon> getParserForType() {
      return PARSER;
    }

    public com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CouponListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CouponList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Coupon coupon = 1;</code>
     */
    java.util.List<com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon> 
        getCouponList();
    /**
     * <code>repeated .Coupon coupon = 1;</code>
     */
    com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon getCoupon(int index);
    /**
     * <code>repeated .Coupon coupon = 1;</code>
     */
    int getCouponCount();
    /**
     * <code>repeated .Coupon coupon = 1;</code>
     */
    java.util.List<? extends com.punyabagus.generalOnlineStore.pojo.CouponData.CouponOrBuilder> 
        getCouponOrBuilderList();
    /**
     * <code>repeated .Coupon coupon = 1;</code>
     */
    com.punyabagus.generalOnlineStore.pojo.CouponData.CouponOrBuilder getCouponOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CouponList}
   */
  public  static final class CouponList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CouponList)
      CouponListOrBuilder {
    // Use CouponList.newBuilder() to construct.
    private CouponList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CouponList() {
      coupon_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CouponList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                coupon_ = new java.util.ArrayList<com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon>();
                mutable_bitField0_ |= 0x00000001;
              }
              coupon_.add(
                  input.readMessage(com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          coupon_ = java.util.Collections.unmodifiableList(coupon_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.punyabagus.generalOnlineStore.pojo.CouponData.internal_static_CouponList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.punyabagus.generalOnlineStore.pojo.CouponData.internal_static_CouponList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList.class, com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList.Builder.class);
    }

    public static final int COUPON_FIELD_NUMBER = 1;
    private java.util.List<com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon> coupon_;
    /**
     * <code>repeated .Coupon coupon = 1;</code>
     */
    public java.util.List<com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon> getCouponList() {
      return coupon_;
    }
    /**
     * <code>repeated .Coupon coupon = 1;</code>
     */
    public java.util.List<? extends com.punyabagus.generalOnlineStore.pojo.CouponData.CouponOrBuilder> 
        getCouponOrBuilderList() {
      return coupon_;
    }
    /**
     * <code>repeated .Coupon coupon = 1;</code>
     */
    public int getCouponCount() {
      return coupon_.size();
    }
    /**
     * <code>repeated .Coupon coupon = 1;</code>
     */
    public com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon getCoupon(int index) {
      return coupon_.get(index);
    }
    /**
     * <code>repeated .Coupon coupon = 1;</code>
     */
    public com.punyabagus.generalOnlineStore.pojo.CouponData.CouponOrBuilder getCouponOrBuilder(
        int index) {
      return coupon_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < coupon_.size(); i++) {
        output.writeMessage(1, coupon_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < coupon_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, coupon_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList)) {
        return super.equals(obj);
      }
      com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList other = (com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList) obj;

      boolean result = true;
      result = result && getCouponList()
          .equals(other.getCouponList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCouponCount() > 0) {
        hash = (37 * hash) + COUPON_FIELD_NUMBER;
        hash = (53 * hash) + getCouponList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CouponList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CouponList)
        com.punyabagus.generalOnlineStore.pojo.CouponData.CouponListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.punyabagus.generalOnlineStore.pojo.CouponData.internal_static_CouponList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.punyabagus.generalOnlineStore.pojo.CouponData.internal_static_CouponList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList.class, com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList.Builder.class);
      }

      // Construct using com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCouponFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (couponBuilder_ == null) {
          coupon_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          couponBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.punyabagus.generalOnlineStore.pojo.CouponData.internal_static_CouponList_descriptor;
      }

      public com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList getDefaultInstanceForType() {
        return com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList.getDefaultInstance();
      }

      public com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList build() {
        com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList buildPartial() {
        com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList result = new com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList(this);
        int from_bitField0_ = bitField0_;
        if (couponBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            coupon_ = java.util.Collections.unmodifiableList(coupon_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.coupon_ = coupon_;
        } else {
          result.coupon_ = couponBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList) {
          return mergeFrom((com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList other) {
        if (other == com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList.getDefaultInstance()) return this;
        if (couponBuilder_ == null) {
          if (!other.coupon_.isEmpty()) {
            if (coupon_.isEmpty()) {
              coupon_ = other.coupon_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCouponIsMutable();
              coupon_.addAll(other.coupon_);
            }
            onChanged();
          }
        } else {
          if (!other.coupon_.isEmpty()) {
            if (couponBuilder_.isEmpty()) {
              couponBuilder_.dispose();
              couponBuilder_ = null;
              coupon_ = other.coupon_;
              bitField0_ = (bitField0_ & ~0x00000001);
              couponBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCouponFieldBuilder() : null;
            } else {
              couponBuilder_.addAllMessages(other.coupon_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon> coupon_ =
        java.util.Collections.emptyList();
      private void ensureCouponIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          coupon_ = new java.util.ArrayList<com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon>(coupon_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon, com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder, com.punyabagus.generalOnlineStore.pojo.CouponData.CouponOrBuilder> couponBuilder_;

      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public java.util.List<com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon> getCouponList() {
        if (couponBuilder_ == null) {
          return java.util.Collections.unmodifiableList(coupon_);
        } else {
          return couponBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public int getCouponCount() {
        if (couponBuilder_ == null) {
          return coupon_.size();
        } else {
          return couponBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon getCoupon(int index) {
        if (couponBuilder_ == null) {
          return coupon_.get(index);
        } else {
          return couponBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public Builder setCoupon(
          int index, com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon value) {
        if (couponBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponIsMutable();
          coupon_.set(index, value);
          onChanged();
        } else {
          couponBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public Builder setCoupon(
          int index, com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder builderForValue) {
        if (couponBuilder_ == null) {
          ensureCouponIsMutable();
          coupon_.set(index, builderForValue.build());
          onChanged();
        } else {
          couponBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public Builder addCoupon(com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon value) {
        if (couponBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponIsMutable();
          coupon_.add(value);
          onChanged();
        } else {
          couponBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public Builder addCoupon(
          int index, com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon value) {
        if (couponBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponIsMutable();
          coupon_.add(index, value);
          onChanged();
        } else {
          couponBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public Builder addCoupon(
          com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder builderForValue) {
        if (couponBuilder_ == null) {
          ensureCouponIsMutable();
          coupon_.add(builderForValue.build());
          onChanged();
        } else {
          couponBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public Builder addCoupon(
          int index, com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder builderForValue) {
        if (couponBuilder_ == null) {
          ensureCouponIsMutable();
          coupon_.add(index, builderForValue.build());
          onChanged();
        } else {
          couponBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public Builder addAllCoupon(
          java.lang.Iterable<? extends com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon> values) {
        if (couponBuilder_ == null) {
          ensureCouponIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, coupon_);
          onChanged();
        } else {
          couponBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public Builder clearCoupon() {
        if (couponBuilder_ == null) {
          coupon_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          couponBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public Builder removeCoupon(int index) {
        if (couponBuilder_ == null) {
          ensureCouponIsMutable();
          coupon_.remove(index);
          onChanged();
        } else {
          couponBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder getCouponBuilder(
          int index) {
        return getCouponFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public com.punyabagus.generalOnlineStore.pojo.CouponData.CouponOrBuilder getCouponOrBuilder(
          int index) {
        if (couponBuilder_ == null) {
          return coupon_.get(index);  } else {
          return couponBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public java.util.List<? extends com.punyabagus.generalOnlineStore.pojo.CouponData.CouponOrBuilder> 
           getCouponOrBuilderList() {
        if (couponBuilder_ != null) {
          return couponBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(coupon_);
        }
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder addCouponBuilder() {
        return getCouponFieldBuilder().addBuilder(
            com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.getDefaultInstance());
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder addCouponBuilder(
          int index) {
        return getCouponFieldBuilder().addBuilder(
            index, com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.getDefaultInstance());
      }
      /**
       * <code>repeated .Coupon coupon = 1;</code>
       */
      public java.util.List<com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder> 
           getCouponBuilderList() {
        return getCouponFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon, com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder, com.punyabagus.generalOnlineStore.pojo.CouponData.CouponOrBuilder> 
          getCouponFieldBuilder() {
        if (couponBuilder_ == null) {
          couponBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon, com.punyabagus.generalOnlineStore.pojo.CouponData.Coupon.Builder, com.punyabagus.generalOnlineStore.pojo.CouponData.CouponOrBuilder>(
                  coupon_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          coupon_ = null;
        }
        return couponBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CouponList)
    }

    // @@protoc_insertion_point(class_scope:CouponList)
    private static final com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList();
    }

    public static com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CouponList>
        PARSER = new com.google.protobuf.AbstractParser<CouponList>() {
      public CouponList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CouponList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CouponList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CouponList> getParserForType() {
      return PARSER;
    }

    public com.punyabagus.generalOnlineStore.pojo.CouponData.CouponList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Coupon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Coupon_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CouponList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CouponList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014coupon.proto\"\233\001\n\006Coupon\022\n\n\002id\030\001 \001(\t\022\014\n" +
      "\004code\030\002 \001(\t\022\014\n\004desc\030\003 \001(\t\022\020\n\010quantity\030\004 " +
      "\001(\005\022\021\n\tstartDate\030\005 \001(\003\022\017\n\007endDate\030\006 \001(\003\022" +
      "\027\n\017discountNominal\030\007 \001(\005\022\032\n\022discountPerc" +
      "entage\030\010 \001(\005\"%\n\nCouponList\022\027\n\006coupon\030\001 \003" +
      "(\0132\007.CouponB4\n&com.punyabagus.generalOnl" +
      "ineStore.pojoB\nCouponData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Coupon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Coupon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Coupon_descriptor,
        new java.lang.String[] { "Id", "Code", "Desc", "Quantity", "StartDate", "EndDate", "DiscountNominal", "DiscountPercentage", });
    internal_static_CouponList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CouponList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CouponList_descriptor,
        new java.lang.String[] { "Coupon", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
