// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.punyabagus.generalOnlineStore.pojo;

public final class ProductData {
  private ProductData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string code = 2;</code>
     */
    boolean hasCode();
    /**
     * <code>optional string code = 2;</code>
     */
    java.lang.String getCode();
    /**
     * <code>optional string code = 2;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>optional string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string desc = 4;</code>
     */
    boolean hasDesc();
    /**
     * <code>optional string desc = 4;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>optional string desc = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>optional int32 quantity = 5;</code>
     */
    boolean hasQuantity();
    /**
     * <code>optional int32 quantity = 5;</code>
     */
    int getQuantity();

    /**
     * <code>optional int64 price = 6;</code>
     */
    boolean hasPrice();
    /**
     * <code>optional int64 price = 6;</code>
     */
    long getPrice();
  }
  /**
   * Protobuf type {@code Product}
   */
  public  static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Product)
      ProductOrBuilder {
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
      id_ = "";
      code_ = "";
      name_ = "";
      desc_ = "";
      quantity_ = 0;
      price_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Product(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              code_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              name_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              desc_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              quantity_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              price_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.punyabagus.generalOnlineStore.pojo.ProductData.internal_static_Product_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.punyabagus.generalOnlineStore.pojo.ProductData.internal_static_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.punyabagus.generalOnlineStore.pojo.ProductData.Product.class, com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object code_;
    /**
     * <code>optional string code = 2;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 4;
    private volatile java.lang.Object desc_;
    /**
     * <code>optional string desc = 4;</code>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string desc = 4;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string desc = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 5;
    private int quantity_;
    /**
     * <code>optional int32 quantity = 5;</code>
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 quantity = 5;</code>
     */
    public int getQuantity() {
      return quantity_;
    }

    public static final int PRICE_FIELD_NUMBER = 6;
    private long price_;
    /**
     * <code>optional int64 price = 6;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 price = 6;</code>
     */
    public long getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, desc_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, quantity_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, price_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, desc_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, quantity_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.punyabagus.generalOnlineStore.pojo.ProductData.Product)) {
        return super.equals(obj);
      }
      com.punyabagus.generalOnlineStore.pojo.ProductData.Product other = (com.punyabagus.generalOnlineStore.pojo.ProductData.Product) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && getCode()
            .equals(other.getCode());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasDesc() == other.hasDesc());
      if (hasDesc()) {
        result = result && getDesc()
            .equals(other.getDesc());
      }
      result = result && (hasQuantity() == other.hasQuantity());
      if (hasQuantity()) {
        result = result && (getQuantity()
            == other.getQuantity());
      }
      result = result && (hasPrice() == other.hasPrice());
      if (hasPrice()) {
        result = result && (getPrice()
            == other.getPrice());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasDesc()) {
        hash = (37 * hash) + DESC_FIELD_NUMBER;
        hash = (53 * hash) + getDesc().hashCode();
      }
      if (hasQuantity()) {
        hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
        hash = (53 * hash) + getQuantity();
      }
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPrice());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.punyabagus.generalOnlineStore.pojo.ProductData.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.punyabagus.generalOnlineStore.pojo.ProductData.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Product)
        com.punyabagus.generalOnlineStore.pojo.ProductData.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.punyabagus.generalOnlineStore.pojo.ProductData.internal_static_Product_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.punyabagus.generalOnlineStore.pojo.ProductData.internal_static_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.punyabagus.generalOnlineStore.pojo.ProductData.Product.class, com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder.class);
      }

      // Construct using com.punyabagus.generalOnlineStore.pojo.ProductData.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        quantity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        price_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.punyabagus.generalOnlineStore.pojo.ProductData.internal_static_Product_descriptor;
      }

      public com.punyabagus.generalOnlineStore.pojo.ProductData.Product getDefaultInstanceForType() {
        return com.punyabagus.generalOnlineStore.pojo.ProductData.Product.getDefaultInstance();
      }

      public com.punyabagus.generalOnlineStore.pojo.ProductData.Product build() {
        com.punyabagus.generalOnlineStore.pojo.ProductData.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.punyabagus.generalOnlineStore.pojo.ProductData.Product buildPartial() {
        com.punyabagus.generalOnlineStore.pojo.ProductData.Product result = new com.punyabagus.generalOnlineStore.pojo.ProductData.Product(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.quantity_ = quantity_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.price_ = price_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.punyabagus.generalOnlineStore.pojo.ProductData.Product) {
          return mergeFrom((com.punyabagus.generalOnlineStore.pojo.ProductData.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.punyabagus.generalOnlineStore.pojo.ProductData.Product other) {
        if (other == com.punyabagus.generalOnlineStore.pojo.ProductData.Product.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCode()) {
          bitField0_ |= 0x00000002;
          code_ = other.code_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000008;
          desc_ = other.desc_;
          onChanged();
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.punyabagus.generalOnlineStore.pojo.ProductData.Product parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.punyabagus.generalOnlineStore.pojo.ProductData.Product) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <code>optional string code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 2;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>optional string desc = 4;</code>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            desc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000008);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 4;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        desc_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>optional int32 quantity = 5;</code>
       */
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 quantity = 5;</code>
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>optional int32 quantity = 5;</code>
       */
      public Builder setQuantity(int value) {
        bitField0_ |= 0x00000010;
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 quantity = 5;</code>
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000010);
        quantity_ = 0;
        onChanged();
        return this;
      }

      private long price_ ;
      /**
       * <code>optional int64 price = 6;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 price = 6;</code>
       */
      public long getPrice() {
        return price_;
      }
      /**
       * <code>optional int64 price = 6;</code>
       */
      public Builder setPrice(long value) {
        bitField0_ |= 0x00000020;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 price = 6;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000020);
        price_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Product)
    }

    // @@protoc_insertion_point(class_scope:Product)
    private static final com.punyabagus.generalOnlineStore.pojo.ProductData.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.punyabagus.generalOnlineStore.pojo.ProductData.Product();
    }

    public static com.punyabagus.generalOnlineStore.pojo.ProductData.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Product(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    public com.punyabagus.generalOnlineStore.pojo.ProductData.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Product product = 1;</code>
     */
    java.util.List<com.punyabagus.generalOnlineStore.pojo.ProductData.Product> 
        getProductList();
    /**
     * <code>repeated .Product product = 1;</code>
     */
    com.punyabagus.generalOnlineStore.pojo.ProductData.Product getProduct(int index);
    /**
     * <code>repeated .Product product = 1;</code>
     */
    int getProductCount();
    /**
     * <code>repeated .Product product = 1;</code>
     */
    java.util.List<? extends com.punyabagus.generalOnlineStore.pojo.ProductData.ProductOrBuilder> 
        getProductOrBuilderList();
    /**
     * <code>repeated .Product product = 1;</code>
     */
    com.punyabagus.generalOnlineStore.pojo.ProductData.ProductOrBuilder getProductOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ProductList}
   */
  public  static final class ProductList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProductList)
      ProductListOrBuilder {
    // Use ProductList.newBuilder() to construct.
    private ProductList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProductList() {
      product_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProductList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                product_ = new java.util.ArrayList<com.punyabagus.generalOnlineStore.pojo.ProductData.Product>();
                mutable_bitField0_ |= 0x00000001;
              }
              product_.add(
                  input.readMessage(com.punyabagus.generalOnlineStore.pojo.ProductData.Product.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          product_ = java.util.Collections.unmodifiableList(product_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.punyabagus.generalOnlineStore.pojo.ProductData.internal_static_ProductList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.punyabagus.generalOnlineStore.pojo.ProductData.internal_static_ProductList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList.class, com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList.Builder.class);
    }

    public static final int PRODUCT_FIELD_NUMBER = 1;
    private java.util.List<com.punyabagus.generalOnlineStore.pojo.ProductData.Product> product_;
    /**
     * <code>repeated .Product product = 1;</code>
     */
    public java.util.List<com.punyabagus.generalOnlineStore.pojo.ProductData.Product> getProductList() {
      return product_;
    }
    /**
     * <code>repeated .Product product = 1;</code>
     */
    public java.util.List<? extends com.punyabagus.generalOnlineStore.pojo.ProductData.ProductOrBuilder> 
        getProductOrBuilderList() {
      return product_;
    }
    /**
     * <code>repeated .Product product = 1;</code>
     */
    public int getProductCount() {
      return product_.size();
    }
    /**
     * <code>repeated .Product product = 1;</code>
     */
    public com.punyabagus.generalOnlineStore.pojo.ProductData.Product getProduct(int index) {
      return product_.get(index);
    }
    /**
     * <code>repeated .Product product = 1;</code>
     */
    public com.punyabagus.generalOnlineStore.pojo.ProductData.ProductOrBuilder getProductOrBuilder(
        int index) {
      return product_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < product_.size(); i++) {
        output.writeMessage(1, product_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < product_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, product_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList)) {
        return super.equals(obj);
      }
      com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList other = (com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList) obj;

      boolean result = true;
      result = result && getProductList()
          .equals(other.getProductList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProductCount() > 0) {
        hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
        hash = (53 * hash) + getProductList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductList)
        com.punyabagus.generalOnlineStore.pojo.ProductData.ProductListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.punyabagus.generalOnlineStore.pojo.ProductData.internal_static_ProductList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.punyabagus.generalOnlineStore.pojo.ProductData.internal_static_ProductList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList.class, com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList.Builder.class);
      }

      // Construct using com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProductFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          productBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.punyabagus.generalOnlineStore.pojo.ProductData.internal_static_ProductList_descriptor;
      }

      public com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList getDefaultInstanceForType() {
        return com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList.getDefaultInstance();
      }

      public com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList build() {
        com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList buildPartial() {
        com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList result = new com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList(this);
        int from_bitField0_ = bitField0_;
        if (productBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            product_ = java.util.Collections.unmodifiableList(product_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.product_ = product_;
        } else {
          result.product_ = productBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList) {
          return mergeFrom((com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList other) {
        if (other == com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList.getDefaultInstance()) return this;
        if (productBuilder_ == null) {
          if (!other.product_.isEmpty()) {
            if (product_.isEmpty()) {
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductIsMutable();
              product_.addAll(other.product_);
            }
            onChanged();
          }
        } else {
          if (!other.product_.isEmpty()) {
            if (productBuilder_.isEmpty()) {
              productBuilder_.dispose();
              productBuilder_ = null;
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProductFieldBuilder() : null;
            } else {
              productBuilder_.addAllMessages(other.product_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.punyabagus.generalOnlineStore.pojo.ProductData.Product> product_ =
        java.util.Collections.emptyList();
      private void ensureProductIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          product_ = new java.util.ArrayList<com.punyabagus.generalOnlineStore.pojo.ProductData.Product>(product_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.punyabagus.generalOnlineStore.pojo.ProductData.Product, com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder, com.punyabagus.generalOnlineStore.pojo.ProductData.ProductOrBuilder> productBuilder_;

      /**
       * <code>repeated .Product product = 1;</code>
       */
      public java.util.List<com.punyabagus.generalOnlineStore.pojo.ProductData.Product> getProductList() {
        if (productBuilder_ == null) {
          return java.util.Collections.unmodifiableList(product_);
        } else {
          return productBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public int getProductCount() {
        if (productBuilder_ == null) {
          return product_.size();
        } else {
          return productBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public com.punyabagus.generalOnlineStore.pojo.ProductData.Product getProduct(int index) {
        if (productBuilder_ == null) {
          return product_.get(index);
        } else {
          return productBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder setProduct(
          int index, com.punyabagus.generalOnlineStore.pojo.ProductData.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.set(index, value);
          onChanged();
        } else {
          productBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder setProduct(
          int index, com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.set(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder addProduct(com.punyabagus.generalOnlineStore.pojo.ProductData.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(value);
          onChanged();
        } else {
          productBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder addProduct(
          int index, com.punyabagus.generalOnlineStore.pojo.ProductData.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(index, value);
          onChanged();
        } else {
          productBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder addProduct(
          com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder addProduct(
          int index, com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder addAllProduct(
          java.lang.Iterable<? extends com.punyabagus.generalOnlineStore.pojo.ProductData.Product> values) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, product_);
          onChanged();
        } else {
          productBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder clearProduct() {
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public Builder removeProduct(int index) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.remove(index);
          onChanged();
        } else {
          productBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder getProductBuilder(
          int index) {
        return getProductFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public com.punyabagus.generalOnlineStore.pojo.ProductData.ProductOrBuilder getProductOrBuilder(
          int index) {
        if (productBuilder_ == null) {
          return product_.get(index);  } else {
          return productBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public java.util.List<? extends com.punyabagus.generalOnlineStore.pojo.ProductData.ProductOrBuilder> 
           getProductOrBuilderList() {
        if (productBuilder_ != null) {
          return productBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(product_);
        }
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder addProductBuilder() {
        return getProductFieldBuilder().addBuilder(
            com.punyabagus.generalOnlineStore.pojo.ProductData.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder addProductBuilder(
          int index) {
        return getProductFieldBuilder().addBuilder(
            index, com.punyabagus.generalOnlineStore.pojo.ProductData.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product product = 1;</code>
       */
      public java.util.List<com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder> 
           getProductBuilderList() {
        return getProductFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.punyabagus.generalOnlineStore.pojo.ProductData.Product, com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder, com.punyabagus.generalOnlineStore.pojo.ProductData.ProductOrBuilder> 
          getProductFieldBuilder() {
        if (productBuilder_ == null) {
          productBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.punyabagus.generalOnlineStore.pojo.ProductData.Product, com.punyabagus.generalOnlineStore.pojo.ProductData.Product.Builder, com.punyabagus.generalOnlineStore.pojo.ProductData.ProductOrBuilder>(
                  product_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          product_ = null;
        }
        return productBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProductList)
    }

    // @@protoc_insertion_point(class_scope:ProductList)
    private static final com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList();
    }

    public static com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProductList>
        PARSER = new com.google.protobuf.AbstractParser<ProductList>() {
      public ProductList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProductList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProductList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductList> getParserForType() {
      return PARSER;
    }

    public com.punyabagus.generalOnlineStore.pojo.ProductData.ProductList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\"`\n\007Product\022\n\n\002id\030\001 \001(\t\022\014" +
      "\n\004code\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\014\n\004desc\030\004 \001(\t" +
      "\022\020\n\010quantity\030\005 \001(\005\022\r\n\005price\030\006 \001(\003\"(\n\013Pro" +
      "ductList\022\031\n\007product\030\001 \003(\0132\010.ProductB5\n&c" +
      "om.punyabagus.generalOnlineStore.pojoB\013P" +
      "roductData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "Id", "Code", "Name", "Desc", "Quantity", "Price", });
    internal_static_ProductList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductList_descriptor,
        new java.lang.String[] { "Product", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
